name: CI/CD Pipeline

on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout do código  
        uses: actions/checkout@v3  

      - name: Configurar ambiente Python  
        uses: actions/setup-python@v4  
        with:  
          python-version: '3.10'  

      - name: Instalar dependências  
        run: |  
          python -m pip install --upgrade pip  
          pip install -r requirements.txt || true  

  test:  
    needs: build  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout do código  
        uses: actions/checkout@v3  

      - name: Rodar testes  
        run: |  
          echo "Executando testes..."
          python -c "print('Testes concluídos')"  

  deploy:  
    needs: test  
    runs-on: ubuntu-latest  
    steps:  
      - name: Deploy de exemplo  
        run: |  
          echo "Deploy realizado com sucesso!"
